// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHXry-dS3CCc4E2yaxnHYdov61zjcVy9Y',
    appId: '1:835640160018:web:3d27c33c2b60b306014dcb',
    messagingSenderId: '835640160018',
    projectId: 'shadman-ecom-flutter-course',
    authDomain: 'shadman-ecom-flutter-course.firebaseapp.com',
    storageBucket: 'shadman-ecom-flutter-course.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmuljTCKHcdSt59zwa3x_ZQF6emM81Cp4',
    appId: '1:835640160018:android:f237e8d726d92f6c014dcb',
    messagingSenderId: '835640160018',
    projectId: 'shadman-ecom-flutter-course',
    storageBucket: 'shadman-ecom-flutter-course.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPAqX9x651rXhSs-Qt5IKtoceRuD9av4o',
    appId: '1:835640160018:ios:2637e9af3b31cab2014dcb',
    messagingSenderId: '835640160018',
    projectId: 'shadman-ecom-flutter-course',
    storageBucket: 'shadman-ecom-flutter-course.appspot.com',
    iosClientId: '835640160018-3k2lv6tvgfstib61c1aoag8muilhjl8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPAqX9x651rXhSs-Qt5IKtoceRuD9av4o',
    appId: '1:835640160018:ios:2637e9af3b31cab2014dcb',
    messagingSenderId: '835640160018',
    projectId: 'shadman-ecom-flutter-course',
    storageBucket: 'shadman-ecom-flutter-course.appspot.com',
    iosClientId: '835640160018-3k2lv6tvgfstib61c1aoag8muilhjl8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
